# Generated by Django 5.0 on 2023-12-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='ID пользователя в Telegram')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название упражнения')),
                ('set', models.PositiveIntegerField(default=1, verbose_name='Подходы')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вес')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тренировки')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('exercises', models.ManyToManyField(blank=True, related_name='Упражнения', to='workout.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.telegramuser')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
    ]
