# Generated by Django 5.0 on 2024-01-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_exercise_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='set',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.workout', verbose_name='Тренировка'),
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.PositiveIntegerField(default=1, verbose_name='Подход')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Вес')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Сет',
                'verbose_name_plural': 'Сеты',
            },
        ),
    ]
