# Generated by Django 5.0 on 2024-01-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='reps',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Повторений'),
        ),
    ]
