# Generated by Django 5.0 on 2024-01-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_sets_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='reps',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, verbose_name='Повторений'),
        ),
    ]
